version: "3.3"
services:
  dev-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "bdaya"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
